### ISSUE TITLE
page down/page up key bug

### ISSUE THREAD

**Issue by lunamoth** [mikecrittenden/shortkeys#286] opened 2019-12-25 03:19 UTC
Thank you for implementing the feature.

But there seems to be a problem.

https://gist.githubusercontent.com/lunamoth/0fba5390f9dc0e939f9f493f832329f3/raw/9d6a67690832a473402bc1ba5bdee9eca39418a6/gistfile1.txt

Page down to 120.

But if you do a page up, it goes up about 30 (90 positions) instead of going up to 120.

I don't know if it's just for me. I am using 4K resolution

**Comment by mikecrittenden** [comment] 2019-12-27 15:01
I personally can't reproduce this. On that gist you sent, it does page up/down the same number of lines each time. The code is just running `window.scrollBy(0,window.innerHeight)` for page down and `window.scrollBy(0,-window.innerHeight)` for page up, so it's not like Shortkeys is doing anything tricky here.

I guess I'll close this issue just because I have no idea what the problem could be and I'm not sure how to go about reproducing it, but if you have any ideas feel free to comment back and I can reopen.

**Closed by mikecrittenden** 2019-12-27 15:01 UTC

**Comment by lunamoth** [comment] 2019-12-28 02:36
Thank you for answer

Thank you for confirming

I'll let you know if it's reproducible
